/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import gerenciartelas.GerenciadorDeTelas;
import javax.swing.JOptionPane;
import model.Professor;

/**
 *
 * @author emanu
 */
public class TelaPrincipalProfessor extends javax.swing.JFrame {
    private TelaCadastrarAula telaCadastrarAula = null;
    private TelaAcessarAvaliacoes telaAcessarAvaliacoes = null;
    private TelaAcessarMedias telaAcessarMedias = null;
    private TelaAlterarSenhaProfessor telaAlterarSenhaProfessor = null;
    private Professor professor;
    
    GerenciadorDeTelas gerenciadorDeTelas;
    /**
     * Creates new form TelaPrincipalProfessor
     */
    public TelaPrincipalProfessor(Professor professor) {
        initComponents();
        this.professor = professor;
        
        this.gerenciadorDeTelas = new GerenciadorDeTelas(desktopPane);
        
    }
    
    public TelaPrincipalProfessor() {
        initComponents();  
        this.gerenciadorDeTelas = new GerenciadorDeTelas(desktopPane);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jToolBar1 = new javax.swing.JToolBar();
        btnSair = new javax.swing.JButton();
        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        cadastrar = new javax.swing.JMenu();
        cadastrarAula = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        acessarAvaliacoes = new javax.swing.JMenuItem();
        acessarMedias = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        alterarSenha = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btnSair.setText("Sair");
        btnSair.setFocusable(false);
        btnSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSair);

        desktopPane.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 248, Short.MAX_VALUE)
        );

        cadastrar.setText("Cadastrar");

        cadastrarAula.setText("Aula");
        cadastrarAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarAulaActionPerformed(evt);
            }
        });
        cadastrar.add(cadastrarAula);

        jMenuBar2.add(cadastrar);

        jMenu4.setText("Acessar");

        acessarAvaliacoes.setText("Avaliações");
        acessarAvaliacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acessarAvaliacoesActionPerformed(evt);
            }
        });
        jMenu4.add(acessarAvaliacoes);

        acessarMedias.setText("Médias");
        acessarMedias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acessarMediasActionPerformed(evt);
            }
        });
        jMenu4.add(acessarMedias);

        jMenuBar2.add(jMenu4);

        jMenu5.setText("Alterar");

        alterarSenha.setText("Senha");
        alterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarSenhaActionPerformed(evt);
            }
        });
        jMenu5.add(alterarSenha);

        jMenuBar2.add(jMenu5);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktopPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarAulaActionPerformed
        // TODO add your handling code here:
        this.telaCadastrarAula = new TelaCadastrarAula(this.professor);
        this.gerenciadorDeTelas.abrirJanelas(telaCadastrarAula);
    }//GEN-LAST:event_cadastrarAulaActionPerformed

    private void acessarAvaliacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acessarAvaliacoesActionPerformed
        // TODO add your handling code here:
        this.telaAcessarAvaliacoes = new TelaAcessarAvaliacoes(this.professor, this.gerenciadorDeTelas);
        this.gerenciadorDeTelas.abrirJanelas(telaAcessarAvaliacoes);
    }//GEN-LAST:event_acessarAvaliacoesActionPerformed

    private void acessarMediasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acessarMediasActionPerformed
        // TODO add your handling code here:
        this.telaAcessarMedias = new TelaAcessarMedias(this.professor);
        this.gerenciadorDeTelas.abrirJanelas(telaAcessarMedias);
    }//GEN-LAST:event_acessarMediasActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new TelaPrincipal().setVisible(true);
    }//GEN-LAST:event_btnSairActionPerformed

    private void alterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarSenhaActionPerformed
        // TODO add your handling code here:
        this.telaAlterarSenhaProfessor = new TelaAlterarSenhaProfessor(this.professor);
        this.gerenciadorDeTelas.abrirJanelas(this.telaAlterarSenhaProfessor);
    }//GEN-LAST:event_alterarSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalProfessor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem acessarAvaliacoes;
    private javax.swing.JMenuItem acessarMedias;
    private javax.swing.JMenuItem alterarSenha;
    private javax.swing.JButton btnSair;
    private javax.swing.JMenu cadastrar;
    private javax.swing.JMenuItem cadastrarAula;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
