/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import gerenciartelas.GerenciadorDeTelas;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author emanu
 */
public class TelaPrincipal extends javax.swing.JFrame {
    private TelaLoginAdministrador telaLoginAdministrador = new TelaLoginAdministrador();
    private TelaLoginAluno telaLoginAluno = new TelaLoginAluno();
    private TelaLoginProfessor telaLoginProfessor = new TelaLoginProfessor();

    GerenciadorDeTelas gerenciadorDeTelas ;
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        gerenciadorDeTelas = new GerenciadorDeTelas(desktopPane);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        brnLogarAdministrador = new javax.swing.JMenuItem();
        btnLoginProfessor = new javax.swing.JMenuItem();
        btnLoginAluno = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        jMenu1.setText("Login");

        brnLogarAdministrador.setText("Administrador");
        brnLogarAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnLogarAdministradorActionPerformed(evt);
            }
        });
        jMenu1.add(brnLogarAdministrador);

        btnLoginProfessor.setText("Professor");
        btnLoginProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginProfessorActionPerformed(evt);
            }
        });
        jMenu1.add(btnLoginProfessor);

        btnLoginAluno.setText("Aluno");
        btnLoginAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginAlunoActionPerformed(evt);
            }
        });
        jMenu1.add(btnLoginAluno);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void brnLogarAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnLogarAdministradorActionPerformed
        // TODO add your handling code here:
        this.gerenciadorDeTelas.abrirJanelas(telaLoginAdministrador);
    }//GEN-LAST:event_brnLogarAdministradorActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnLoginAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginAlunoActionPerformed
        // TODO add your handling code here:
        this.gerenciadorDeTelas.abrirJanelas(telaLoginAluno);
    }//GEN-LAST:event_btnLoginAlunoActionPerformed

    private void btnLoginProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginProfessorActionPerformed
        // TODO add your handling code here:
        this.gerenciadorDeTelas.abrirJanelas(telaLoginProfessor);
    }//GEN-LAST:event_btnLoginProfessorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem brnLogarAdministrador;
    private javax.swing.JMenuItem btnLoginAluno;
    private javax.swing.JMenuItem btnLoginProfessor;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables

    private void close() {
        this.setVisible(false);
    }
}
