/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import gerenciartelas.GerenciadorDeTelas;
import model.Administrador;

/**
 *
 * @author emanu
 */
public class TelaPrincipalAdministrador extends javax.swing.JFrame {
    private TelaCadastrarAluno telaCadastrarAluno = null;
    private TelaAlterarAluno telaAlterarAluno = null;
    private TelaAlterarProfessor telaAlterarProfessor = null;
    private TelaExcluirAluno telaExcluirAluno = null;
    private TelaExcluirProfessor telaExcluirProfessor = null;
    private TelaCadastroProfessor telaCadastrarProfessor = null;
    private Administrador administrador;
    
    GerenciadorDeTelas gerenciadorDeTelas;
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipalAdministrador() {  
        initComponents();
    }
    public TelaPrincipalAdministrador(Administrador administrador) {
        this.administrador = administrador;
        initComponents();
        gerenciadorDeTelas = new GerenciadorDeTelas(desktopPane);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnSair = new javax.swing.JButton();
        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cadastrarAluno = new javax.swing.JMenuItem();
        cadastrarProfessor = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        alterarAluno = new javax.swing.JMenuItem();
        alterarProf = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        excluirAluno = new javax.swing.JMenuItem();
        excluirProf = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btnSair.setText("Sair");
        btnSair.setFocusable(false);
        btnSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSair);

        desktopPane.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 248, Short.MAX_VALUE)
        );

        jMenu1.setText("Cadastrar");

        cadastrarAluno.setText("Aluno");
        cadastrarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarAlunoActionPerformed(evt);
            }
        });
        jMenu1.add(cadastrarAluno);

        cadastrarProfessor.setText("Professor");
        cadastrarProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarProfessorActionPerformed(evt);
            }
        });
        jMenu1.add(cadastrarProfessor);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Alterar");

        alterarAluno.setText("Aluno");
        alterarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarAlunoActionPerformed(evt);
            }
        });
        jMenu3.add(alterarAluno);

        alterarProf.setText("Professor");
        alterarProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarProfActionPerformed(evt);
            }
        });
        jMenu3.add(alterarProf);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Excluir");

        excluirAluno.setText("Aluno");
        excluirAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirAlunoActionPerformed(evt);
            }
        });
        jMenu4.add(excluirAluno);

        excluirProf.setText("Professor");
        excluirProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirProfActionPerformed(evt);
            }
        });
        jMenu4.add(excluirProf);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktopPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarAlunoActionPerformed
        // TODO add your handling code here:
        telaCadastrarAluno = new TelaCadastrarAluno();
        this.gerenciadorDeTelas.abrirJanelas(telaCadastrarAluno);
    }//GEN-LAST:event_cadastrarAlunoActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new TelaPrincipal().setVisible(true);
    }//GEN-LAST:event_btnSairActionPerformed

    private void alterarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarAlunoActionPerformed
        // TODO add your handling code here:
        telaAlterarAluno = new TelaAlterarAluno();
        this.gerenciadorDeTelas.abrirJanelas(telaAlterarAluno);
    }//GEN-LAST:event_alterarAlunoActionPerformed

    private void alterarProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarProfActionPerformed
        // TODO add your handling code here:
        telaAlterarProfessor = new TelaAlterarProfessor();
        this.gerenciadorDeTelas.abrirJanelas(telaAlterarProfessor);
    }//GEN-LAST:event_alterarProfActionPerformed

    private void excluirAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirAlunoActionPerformed
        // TODO add your handling code here:
        telaExcluirAluno = new TelaExcluirAluno();
        this.gerenciadorDeTelas.abrirJanelas(telaExcluirAluno);
    }//GEN-LAST:event_excluirAlunoActionPerformed

    private void excluirProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirProfActionPerformed
        // TODO add your handling code here:
        telaExcluirProfessor = new TelaExcluirProfessor();
        this.gerenciadorDeTelas.abrirJanelas(telaExcluirProfessor);
    }//GEN-LAST:event_excluirProfActionPerformed

    private void cadastrarProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarProfessorActionPerformed
        // TODO add your handling code here:
        telaCadastrarProfessor = new TelaCadastroProfessor();
        this.gerenciadorDeTelas.abrirJanelas(telaCadastrarProfessor);
    }//GEN-LAST:event_cadastrarProfessorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem alterarAluno;
    private javax.swing.JMenuItem alterarProf;
    private javax.swing.JButton btnSair;
    private javax.swing.JMenuItem cadastrarAluno;
    private javax.swing.JMenuItem cadastrarProfessor;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem excluirAluno;
    private javax.swing.JMenuItem excluirProf;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
