/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerAvaliacao;
import javax.swing.JOptionPane;
import model.Aluno;

/**
 *
 * @author emanu
 */
public class TelaAvaliarAula extends javax.swing.JInternalFrame {
    private int idAula;
    private String disciplina;
    private String conteudo;
    private String data;
    private String horario;
    private String semestre;
    private Aluno aluno;
    private TelaAcessarAulas telaAcessarAulas;
    /**
     * Creates new form TelaAvaliarAula
     */
    public TelaAvaliarAula(int idAula, String disciplina,String  conteudo,String  professor,String  data, String horario,String  semestre, Aluno aluno, TelaAcessarAulas telaAcessarAulas) {
        initComponents();
        
        this.telaAcessarAulas = telaAcessarAulas;
        this.idAula = idAula;
        this.disciplina = disciplina;
        this.conteudo = conteudo;
        this.data = data;
        this.horario = horario;
        this.semestre = semestre;
        this.aluno = aluno;
        
        txtDisciplina.setText(disciplina);
        txtConteudo.setText(conteudo);
        txtData.setText(data);
        txtHora.setText(horario);
        txtProfessor.setText(professor);
        txtSemestre.setText(semestre);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtDisciplina = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtProfessor = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtConteudo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtData = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnAvaliar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtHora = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtSemestre = new javax.swing.JLabel();
        txtParecer = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtNota = new javax.swing.JFormattedTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Avaliar Aula");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Disciplina:");

        txtDisciplina.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtDisciplina.setText("Densenvovilmento de Sistemas Web");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Professor:");

        txtProfessor.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtProfessor.setText("Daniel");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Conteúdo:");

        txtConteudo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtConteudo.setText("Transaction");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Data:");

        txtData.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtData.setText("13/11/2018");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setText("Nota:");

        btnAvaliar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnAvaliar.setText("Avaliar");
        btnAvaliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvaliarActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setText("Hora:");

        txtHora.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtHora.setText("7h15-8h55");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel12.setText("Semestre: ");

        txtSemestre.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtSemestre.setText("2018.2");

        txtParecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtParecerActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel14.setText("Parecer:");

        try {
            txtNota.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNota.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSemestre))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtProfessor))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtConteudo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtDisciplina))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel14)
                            .addComponent(jLabel7))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHora)
                            .addComponent(txtData)
                            .addComponent(txtNota, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(txtParecer))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAvaliar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDisciplina))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtConteudo)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtProfessor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtSemestre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtData)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHora)
                    .addComponent(jLabel10))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNota, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(txtParecer, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAvaliar)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtParecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtParecerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtParecerActionPerformed

    private void btnAvaliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvaliarActionPerformed
        // TODO add your handling code here:
        try{
            double nota = Double.parseDouble((String)txtNota.getText());
            String parecer  = txtParecer.getText();
            ControllerAvaliacao ca = new ControllerAvaliacao();
            String mensagem = ca.avaliar(idAula, nota, parecer, disciplina, conteudo, horario, semestre, aluno);
            JOptionPane.showMessageDialog(null, mensagem);
            this.setVisible(false);
            this.telaAcessarAulas.dispose();
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(null, "Você precisa digitar uma nota!");
        }
        
    }//GEN-LAST:event_btnAvaliarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvaliar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel txtConteudo;
    private javax.swing.JLabel txtData;
    private javax.swing.JLabel txtDisciplina;
    private javax.swing.JLabel txtHora;
    private javax.swing.JFormattedTextField txtNota;
    private javax.swing.JTextField txtParecer;
    private javax.swing.JLabel txtProfessor;
    private javax.swing.JLabel txtSemestre;
    // End of variables declaration//GEN-END:variables
}
